spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  data:
    mongodb:
      #uri: mongodb://xxxx:xxx@127.0.0.1:27017/demo   #mongodb://账户:密码@ip:端口/数据库名
      uri: mongodb://localhost/demo